namespace SkyrimCraftingTool;

public enum ArmorSlot
{
    Head = 30,
    Hair = 31,
    Body = 32,
    Hands = 33,
    Forearms = 34,
    Amulet = 35,
    Ring = 36,
    Feet = 37,
    Calves = 38,
    Shield = 39,
    Tail = 40,
    LongHair = 41,
    Circlet = 42,
    Ears = 43,
    FaceMouth = 44,
    NeckCapeScarf = 45,
    ChestPrimary = 46,
    Back = 47,
    MiscFx1 = 48,
    PelvisPrimary = 49,
    DecapitatedHead = 50,
    DecapitateFx = 51,
    PelvisSecondary = 52,
    LegPrimary = 53,
    LegSecondary = 54,
    FaceAltJewelry = 55,
    ChestSecondary = 56,
    Shoulders = 57,
    ArmSecondary = 58,
    ArmPrimary = 59,
    MiscFx2 = 60,
    FX01 = 61,
}
