using Noggog;
using System.Collections.ObjectModel;
using System.IO;
using System.Text;
using System.Windows.Input;

namespace SkyrimCraftingTool
{
    public class VendorSkyPatcherViewModel
    {

        public string EspName { get; }
        public ObservableCollection<ItemCardVM> Items { get; }

        public ObservableCollection<VendorCategoryVM> Categories { get; }

        public ICommand CreateVendorSkyPatcherPatch { get; }


        public VendorSkyPatcherViewModel(IEnumerable<ItemCardVM> items, string espName)
        {
            EspName = espName ?? "Unknown.esp";

            Items = new ObservableCollection<ItemCardVM>(items);

            CreateVendorSkyPatcherPatch = new RelayCommand(_ => ExecuteVendorSkyPatcherPatch());

            Categories = new ObservableCollection<VendorCategoryVM>(
            GlobalState.VendorCategories.Select(cat =>
            {
                var vm = new VendorCategoryVM
                {
                    CategoryName = cat.CategoryKey,
                    IniFileName = cat.IniFileName,
                    Vendors = new ObservableCollection<VendorOption>(
                    cat.Vendors.Select(v => new VendorOption { Name = v })
                )
                };

                vm.SelectAllCommand = new RelayCommand(_ =>
                {
                    foreach (var vendor in vm.Vendors)
                        vendor.IsSelected = true;
                });

                return vm;
            })
            );


        }

        private void ExecuteVendorSkyPatcherPatch()
        {
            try
            {
                string baseDir = AppContext.BaseDirectory;

                string rootFolder = Path.Combine(
                    baseDir,
                    "Output",
                    "SKSE",
                    "Plugins",
                    "SkyPatcher",
                    "container"
                );

                Directory.CreateDirectory(rootFolder);

                string espFolder = Path.Combine(rootFolder, EspName);
                Directory.CreateDirectory(espFolder);

                string containerFolder = Path.Combine(espFolder, "container");
                Directory.CreateDirectory(containerFolder);

                bool anyCategoryWritten = false;

                foreach (var category in Categories)
                {
                    var selectedVendors = category.Vendors.Where(v => v.IsSelected).ToList();
                    if (!selectedVendors.Any())
                        continue;

                    anyCategoryWritten = true;

                    string iniPath = Path.Combine(containerFolder, category.IniFileName);

                    var sb = new StringBuilder();
                    sb.AppendLine("; Generated by SkyrimCraftingTool");
                    sb.AppendLine();

                    foreach (var vendor in selectedVendors)
                    {
                        if (!GlobalState.VendorChestFormIDs.TryGetValue(vendor.Name, out string containerFormID))
                            continue;

                        foreach (var item in Items)
                        {
                            string formID = item.Record.FormKey.ID.ToString("X8");

                            sb.AppendLine(
                                $"filterByContainers=Skyrim.esm|{containerFormID}:addToContainers={EspName}|{formID}~1"
                            );
                        }

                        sb.AppendLine();
                    }

                    File.WriteAllText(iniPath, sb.ToString());
                }

                if (!anyCategoryWritten)
                {
                    System.Windows.MessageBox.Show("No vendors selected in any category.");
                    return;
                }

                System.Windows.MessageBox.Show("VendorSkyPatcher Patch generated.");
            }
            catch (Exception ex)
            {
                System.Windows.MessageBox.Show("SkyPatcher Error:\n" + ex.Message);
            }
        }

    }

}
