using Noggog;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Input;

namespace SkyrimCraftingTool
{
    public class VendorSkyPatcherViewModel
    {

        public string EspName { get; }
        public ObservableCollection<ItemCardVM> Items { get; }
        public ObservableCollection<VendorOption> VendorOptions { get; }

        public ICommand CreateVendorSkyPatcherPatch { get; }

        public VendorSkyPatcherViewModel(IEnumerable<ItemCardVM> items, string espName)
        {
            EspName = espName ?? "Unknown.esp";

            Items = new ObservableCollection<ItemCardVM>(items);

            VendorOptions = new ObservableCollection<VendorOption>(
                GlobalState.VendorSkyPatcher.Select(v => new VendorOption
                {
                    Name = v,
                    IsSelected = false
                })
            );

            CreateVendorSkyPatcherPatch = new RelayCommand(_ => ExecuteVendorSkyPatcherPatch());
        }

        public List<string> GetSelectedVendors()
        {
            return VendorOptions
                .Where(v => v.IsSelected)
                .Select(v => v.Name)
                .ToList();
        }

        private void ExecuteVendorSkyPatcherPatch()
        {
            try
            {
                string baseDir = AppContext.BaseDirectory;

                string rootFolder = Path.Combine(
                    baseDir,
                    "Output",
                    "SKSE",
                    "Plugins",
                    "SkyPatcher",
                    "container"
                );

                Directory.CreateDirectory(rootFolder);

                string espFolder = Path.Combine(rootFolder, EspName);
                Directory.CreateDirectory(espFolder);

                string containerFolder = Path.Combine(espFolder, "container");
                Directory.CreateDirectory(containerFolder);

                string iniPath = Path.Combine(containerFolder, "blacksmith.ini");

                var sb = new StringBuilder();
                sb.AppendLine("; Generated by SkyrimCraftingTool");
                sb.AppendLine();

                var selectedVendors = GetSelectedVendors();
                if (selectedVendors.Count == 0)
                {
                    System.Windows.MessageBox.Show("No vendors selected.");
                    return;
                }

                foreach (var vendor in selectedVendors)
                {
                    if (!GlobalState.VendorChestFormIDs.TryGetValue(vendor, out string containerFormID))
                        continue;

                    foreach (var item in Items)
                    {
                        string formID = item.Record.FormKey.ID.ToString("X8");

                        sb.AppendLine(
                            $"filterByContainers=Skyrim.esm|{containerFormID}:addToContainers={EspName}|{formID}~1"
                        );
                    }

                    sb.AppendLine();
                }

                File.WriteAllText(iniPath, sb.ToString());

                System.Windows.MessageBox.Show("VendorSkyPatcher Patch generated:\n" + iniPath);
            }
            catch (Exception ex)
            {
                System.Windows.MessageBox.Show("SkyPatcher Error:\n" + ex.Message);
            }
        }

    }
}
