using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using SkyrimCraftingTool.Model;

namespace SkyrimCraftingTool.Services
{
    // MO2's mod priority, read from profiles\<profile>\modlist.txt.
    //
    // WHY THE TOOL NEEDS IT: the same plugin file name can exist in several mod folders, and until
    // now every copy was parsed (see PluginPathPicker for the whole story). modlist.txt is the only
    // place that says which one MO2 actually hands to the game.
    //
    // THE FILE FORMAT, verified against a real portable instance (2026-10-05, 315 lines):
    //   "# This file was automatically generated by Mod Organizer."  comment, first line
    //   "+Some Mod"        enabled  - a real folder under mods\
    //   "-Some Mod"        DISABLED - the folder exists, but MO2 does not load it
    //   "*DLC: Dawnguard"  managed entry for game content; NOT a folder under mods\
    //   "-Late Loaders_separator"  a separator row in the MO2 UI, not a mod
    //
    // THE ORDER IS TOP-WINS. The first line is the highest priority. Verified the same way rather
    // than assumed: in the real file the DLCs and the Creation Club entries sit at the very BOTTOM,
    // and those are the things every mod overrides.
    public sealed class ModListOrder
    {
        public static ModListOrder Empty { get; } = new(Array.Empty<string>(), Array.Empty<string>());

        // Highest priority first.
        public IReadOnlyList<string> EnabledHighestFirst { get; }

        private readonly Dictionary<string, int> _rankByName;
        private readonly HashSet<string> _disabled;

        private ModListOrder(IReadOnlyList<string> enabledHighestFirst, IEnumerable<string> disabled)
        {
            EnabledHighestFirst = enabledHighestFirst;

            _rankByName = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
            for (int i = 0; i < enabledHighestFirst.Count; i++)
                _rankByName.TryAdd(enabledHighestFirst[i], i);

            _disabled = new HashSet<string>(disabled, StringComparer.OrdinalIgnoreCase);
        }

        public bool IsEmpty => _rankByName.Count == 0 && _disabled.Count == 0;

        // Lower wins. int.MaxValue for a folder the list does not mention, so an unknown mod sorts
        // after every known one instead of jumping to the front - a mod folder that is on disk but
        // not in modlist.txt is a half-installed state, not a high-priority one.
        public int RankOf(string modFolderName) =>
            modFolderName != null && _rankByName.TryGetValue(modFolderName, out var rank)
                ? rank
                : int.MaxValue;

        public bool IsDisabled(string modFolderName) =>
            modFolderName != null && _disabled.Contains(modFolderName);

        public static ModListOrder Parse(IEnumerable<string> lines)
        {
            if (lines == null) return Empty;

            var enabled = new List<string>();
            var disabled = new List<string>();

            foreach (var raw in lines)
            {
                if (string.IsNullOrWhiteSpace(raw)) continue;

                var line = raw.Trim();
                if (line.StartsWith("#", StringComparison.Ordinal)) continue;

                // '*' rows are MO2's managed game content (DLC, Creation Club). They have no folder
                // under mods\, so they can never be a candidate path and are irrelevant here.
                if (line.StartsWith("*", StringComparison.Ordinal)) continue;

                char marker = line[0];
                if (marker != '+' && marker != '-') continue;

                var name = line.Substring(1).Trim();
                if (name.Length == 0) continue;

                // Separator rows are UI furniture. MO2 writes them with the same +/- marker, so the
                // suffix is the only thing that tells them apart.
                if (name.EndsWith("_separator", StringComparison.OrdinalIgnoreCase)) continue;

                if (marker == '+') enabled.Add(name);
                else disabled.Add(name);
            }

            return new ModListOrder(enabled, disabled);
        }

        public static ModListOrder Read(string modListFilePath)
        {
            if (string.IsNullOrWhiteSpace(modListFilePath) || !File.Exists(modListFilePath))
                return Empty;

            try
            {
                return Parse(File.ReadAllLines(modListFilePath));
            }
            catch (Exception ex)
            {
                // A missing or unreadable modlist.txt must never stop a scan. Without it the picker
                // falls back to its manager-agnostic rule, which is worse but still deterministic.
                AppLogger.LogError($"ModListOrder.Read({modListFilePath})", ex);
                return Empty;
            }
        }
    }
}
