using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace SkyrimCraftingTool.Services.PatchGen
{
    // Orchestrates the patch export:
    //  - edited ARMO/WEAP fields  -> SkyPatcher INIs, one <Plugin>.esp.ini per source plugin
    //  - edited / created COBJ    -> one generated ESP (SkyrimCraftingTool.esp)
    // See docs/PatchGenerator-Plan.md.
    public sealed class PatchGeneratorService
    {
        private readonly PatchDataReader _itemReader;
        private readonly CobjPatchReader _cobjReader;
        private readonly PatchFormIdMapStore _formIdMap;
        private readonly IReferenceResolver? _references;

        public PatchGeneratorService(
            string? connString = null,
            IReferenceResolver? references = null,
            PatchDataReader? itemReader = null,
            CobjPatchReader? cobjReader = null,
            PatchFormIdMapStore? formIdMap = null)
        {
            _itemReader = itemReader ?? new PatchDataReader(connString);
            _cobjReader = cobjReader ?? new CobjPatchReader(connString);
            _formIdMap = formIdMap ?? new PatchFormIdMapStore(connString);
            _references = references;
        }

        public PatchGenReport Generate(PatchGenOptions options)
        {
            var report = new PatchGenReport();

            GenerateSkyPatcher(options, report);

            if (options.GenerateCobj)
                GenerateCobj(options, report);

            return report;
        }

        // --- SkyPatcher (Phase A) ---

        private void GenerateSkyPatcher(PatchGenOptions options, PatchGenReport report)
        {
            var armorByPlugin = new Dictionary<string, List<SkyPatcherRule>>(StringComparer.OrdinalIgnoreCase);
            foreach (var pair in _itemReader.ReadEditedArmor())
            {
                var rule = ItemRuleBuilder.BuildArmorRule(pair.Original, pair.Edited, out var skip);
                if (Accept(rule, skip, report))
                    report.ArmorRuleCount += Add(armorByPlugin, rule!);
            }

            var weaponByPlugin = new Dictionary<string, List<SkyPatcherRule>>(StringComparer.OrdinalIgnoreCase);
            foreach (var pair in _itemReader.ReadEditedWeapons())
            {
                var rule = ItemRuleBuilder.BuildWeaponRule(pair.Original, pair.Edited, out var skip);
                if (Accept(rule, skip, report))
                    report.WeaponRuleCount += Add(weaponByPlugin, rule!);
            }

            if (options.DryRun) return;

            WriteCategory(options, "armor", armorByPlugin, report);
            WriteCategory(options, "weapon", weaponByPlugin, report);
        }

        private bool Accept(SkyPatcherRule? rule, ItemRuleBuilder.NameSkip? skip, PatchGenReport report)
        {
            if (skip != null)
                report.Warnings.Add(
                    $"Name edit skipped for {skip.Key}: \"{skip.Name}\" contains a character " +
                    "(~ : newline) SkyPatcher can't express in fullName.");

            if (rule == null) return false;

            foreach (var keyword in rule.ReferencedKeywordKeys)
                if (_references != null && !_references.IsActive(keyword))
                    report.Warnings.Add(
                        $"{rule.TargetPlugin}|{rule.TargetFormId}: keyword {keyword} is not in the " +
                        "current scan (rule still written).");

            return true;
        }

        private static int Add(Dictionary<string, List<SkyPatcherRule>> byPlugin, SkyPatcherRule rule)
        {
            if (!byPlugin.TryGetValue(rule.TargetPlugin, out var list))
                byPlugin[rule.TargetPlugin] = list = new List<SkyPatcherRule>();
            list.Add(rule);
            return 1;
        }

        private static void WriteCategory(
            PatchGenOptions options, string category,
            Dictionary<string, List<SkyPatcherRule>> byPlugin, PatchGenReport report)
        {
            var dir = options.CategoryDir(category);

            // Only ever our own priority subfolder — never the shared category root where other
            // mods' SkyPatcher files live. Wipe it so a plugin whose items are all un-edited now
            // loses its stale file.
            if (Directory.Exists(dir))
                Directory.Delete(dir, recursive: true);

            if (byPlugin.Count == 0)
                return;

            Directory.CreateDirectory(dir);

            foreach (var (plugin, rules) in byPlugin.OrderBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase))
            {
                var ordered = rules
                    .OrderBy(r => r.TargetFormId, StringComparer.OrdinalIgnoreCase)
                    .ToList();

                var header =
                    "Generated by SkyrimCraftingTool. Do not edit by hand — regenerated on every export.\n" +
                    $"Source plugin: {plugin}";

                var text = SkyPatcherIniWriter.Write(ordered, header);
                var path = Path.Combine(dir, plugin + ".ini");
                File.WriteAllText(path, text);
                report.WrittenFiles.Add(path);
            }
        }

        // --- COBJ ESP (Phase B) ---

        private void GenerateCobj(PatchGenOptions options, PatchGenReport report)
        {
            var entries = _cobjReader.ReadEditedCobj();
            if (entries.Count == 0) return;

            if (options.DryRun)
            {
                report.CobjNewCount = entries.Count(e => e.IsNew);
                report.CobjOverrideCount = entries.Count(e => !e.IsNew);
                return;
            }

            var loadOrder = LoadOrderReader.Read();
            var builder = new CobjEspBuilder();
            var masters = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);
            bool allEsl = true;
            var espPaths = new List<string>();

            var groups = entries
                .GroupBy(e => options.EspNameFor(e.SourcePlugin), StringComparer.OrdinalIgnoreCase)
                .OrderBy(g => g.Key, StringComparer.OrdinalIgnoreCase);

            foreach (var g in groups)
            {
                var res = builder.Build(
                    g.ToList(), _formIdMap, loadOrder, options.OutputRoot, g.Key, options.EslWhenPossible);

                report.CobjNewCount += res.NewCount;
                report.CobjOverrideCount += res.OverrideCount;
                report.Warnings.AddRange(res.Warnings);
                report.WrittenFiles.Add(res.OutputPath);
                espPaths.Add(res.OutputPath);
                foreach (var m in res.Masters) masters.Add(m);
                if (res.NewCount + res.OverrideCount > 0 && !res.EslFlagged) allEsl = false;
            }

            report.CobjEspPath = espPaths.Count == 1 ? espPaths[0] : null;
            report.CobjEslFlagged = espPaths.Count > 0 && allEsl;
            report.CobjMasters = masters.ToList();
        }
    }
}
